### ISSUE TITLE
看到您Reuse的例子有个疑问

### ISSUE THREAD

**Issue by jiazufei** [allenhsu/UIScrollView-Samples#1]
我在做缓存刷新页面的时候，不知道应该刷新哪一个viewctroller，我对数据做了有顺序的缓存缓存处理，但viewctroller 是重用的，所以对应刷新数据的时候会错乱，我不清楚在哪里刷新才能保证数据是正确的，请指点，非常感谢

**Comment by allenhsu** [comment]
可以多一个 Dictionary 来映射 VC 和 model 的关系
