### ISSUE TITLE
Lazyload里请求的连接已经没有用了

### ISSUE THREAD

**Issue by shinancao** [allenhsu/UIScrollView-Samples#2]
1、Demo请求的图片链接已经失效
static NSString *apiURL = @"http://image.baidu.com/i?tn=resultjson_com&word=cat&rn=60";

如果可能，希望作者改一个正常请求的，否则没办法演示- -!

2、对于shouldLoadImage的判断
if (![cache imageFromMemoryCacheForKey:key]) {
                shouldLoadImage = NO;
}
这块是否有问题，不应该是if ([cache imageFromMemoryCacheForKey:key])吗？怎么判断为nil了，还不去加载呢

**Comment by allenhsu** [comment]
1. demo link 已经 fix 了
2. 这个 `if` 要跟外面的 `if` 一起看，外面的 `self.targetRect && !CGRectIntersectsRect([self.targetRect CGRectValue], cellFrame)` 表示当前 cell 不在目标 rect 区域，两个 `if` 合起来的意思是：如果不在目标 rect 而且内存里没有缓存的，就不 load，如果在目标区域，或者在内存里有缓存的，就 load。

**Comment by shinancao** [comment]
嗯嗯，谢谢解答=。=
